/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Button1: typeof import('./src/components/Button/Button1.vue')['default']
    Button2: typeof import('./src/components/Button/Button2.vue')['default']
    Card2: typeof import('./src/components/Card/Card2.vue')['default']
    Card3: typeof import('./src/components/Card/Card3.vue')['default']
    Card4: typeof import('./src/components/Card/Card4.vue')['default']
    DataCard: typeof import('./src/components/Card/DataCard.vue')['default']
    Dialog1: typeof import('./src/components/Dialog/Dialog1.vue')['default']
    Header1: typeof import('./src/components/Header/Header1.vue')['default']
    Header2: typeof import('./src/components/Header/Header2.vue')['default']
    IconCard1: typeof import('./src/components/Card/IconCard1.vue')['default']
    IconCard2: typeof import('./src/components/Card/IconCard2.vue')['default']
    LineTitle: typeof import('./src/components/Title/LineTitle.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    Timeline: typeof import('./src/components/Timeline/Timeline.vue')['default']
    Title2: typeof import('./src/components/Title/Title2.vue')['default']
    TitleCard: typeof import('./src/components/Card/TitleCard.vue')['default']
  }
}
